import type { Locale } from "@/lib/i18n";

const IX: Record<string, string> = {
  IMAO: "MAOIs",
  "IMAO (potentialisation forte)": "MAOIs (strong potentiation)",
  "IMAO (sauf ayahuasca encadrée)": "MAOIs (except guided ayahuasca)",
  Tramadol: "Tramadol",
  Alcool: "Alcohol",
  "Alcool (cocaéthylène, toxique)": "Alcohol (cocaethylene, toxic)",
  "Alcool (malaise)": "Alcohol (illness)",
  Opioïdes: "Opioids",
  "Autres opioïdes": "Other opioids",
  "Opioïdes (speedball)": "Opioids (speedball)",
  GHB: "GHB",
  "Autres stimulants": "Other stimulants",
  Stimulants: "Stimulants",
  "Stimulants (masque l’ivresse)": "Stimulants (mask intoxication)",
  "Dépresseurs (alcool, opioïdes, benzo)": "Depressants (alcohol, opioids, benzos)",
  Dépresseurs: "Depressants",
  ISRS: "SSRIs",
  "ISRS (syndrome sérotoninergique rare)": "SSRIs (rare serotonin syndrome)",
  "Autres anticholinergiques": "Other anticholinergics",
  Benzodiazépines: "Benzodiazepines",
  Kétamine: "Ketamine",
  MDMA: "MDMA",
  Lithium: "Lithium",
  "Debout (risque de chute/syncope)": "Standing (fall/syncope risk)",
  Psychédéliques: "Psychedelics",
  "Psychédéliques (amplification)": "Psychedelics (amplification)",
  "Sildénafil/Viagra (chute de tension mortelle)": "Sildenafil/Viagra (fatal blood-pressure drop)",
  Vasoconstricteurs: "Vasoconstrictors",
  Cannabis: "Cannabis",
  "Contraceptifs (efficacité réduite)": "Contraceptives (reduced efficacy)",
};

const EFFECT: Record<string, string> = {
  Anxiété: "Anxiety",
  Euphorie: "Euphoria",
  "Pupilles dilatées": "Dilated pupils",
  "Distorsion du temps": "Time distortion",
  Confusion: "Confusion",
  Détente: "Relaxation",
  Tachycardie: "Tachycardia",
  Introspection: "Introspection",
  "Pensée créative": "Creative thinking",
  "Bad trip possible": "Possible bad trip",
  Sédation: "Sedation",
  Visuels: "Visuals",
  Amnésie: "Amnesia",
  Insomnie: "Insomnia",
  Concentration: "Focus",
  Somnolence: "Drowsiness",
  Éveil: "Wakefulness",
  Anxiolyse: "Anxiolysis",
  "Relaxation musculaire": "Muscle relaxation",
  "Dépression respiratoire (en mélange)": "Respiratory depression (in mixes)",
  Dépendance: "Dependence",
  Énergie: "Energy",
  "Perte d’appétit": "Appetite loss",
  "Perte d'appétit": "Appetite loss",
  Confiance: "Confidence",
  Descente: "Come-down",
  "Effets variables": "Variable effects",
  Rires: "Laughter",
  "Bouche sèche": "Dry mouth",
  Paranoïa: "Paranoia",
  Appétit: "Appetite",
  "Yeux rouges": "Red eyes",
  Nausées: "Nausea",
  Dissociation: "Dissociation",
  Rêverie: "Daydreaming",
  Ataxie: "Ataxia",
  Désorientation: "Disorientation",
  Distorsions: "Distortions",
  "Maux de tête": "Headache",
  Mémoire: "Memory",
  "Détente (dose élevée)": "Relaxation (high dose)",
  "Détente profonde": "Deep relaxation",
  "Dépression respiratoire": "Respiratory depression",
  "Réalités alternatives": "Alternate realities",
  "Sentiment d’unité": "Sense of unity",
  "Détente paradoxale": "Paradoxical relaxation",
  "Descente marquée": "Marked come-down",
  "Syndrome sérotoninergique": "Serotonin syndrome",
  "Distorsion temporelle extrême": "Extreme time distortion",
  "Géométrie complexe": "Complex geometry",
  Légèreté: "Lightness",
  "Trous de mémoire": "Memory gaps",
  "Énergie (faible dose)": "Energy (low dose)",
  "Nausées (débutant)": "Nausea (come-up)",
  "Chaleur émotionnelle": "Emotional warmth",
  "Bouffée euphorique": "Euphoric rush",
  "Arrêt respiratoire": "Respiratory arrest",
  Analgésie: "Analgesia",
  "Atteinte vésicale (usage chronique)": "Bladder damage (chronic use)",
  Positif: "Positive",
  Neutre: "Neutral",
  Négatif: "Negative",
};

export function translateInteraction(label: string, locale: Locale) {
  if (locale !== "en") return label;
  return IX[label] || IX[label.replace("'", "’")] || label;
}

export function translateEffect(label: string, locale: Locale) {
  if (locale !== "en") return label;
  return EFFECT[label] || EFFECT[label.replace("'", "’")] || label;
}
