/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as EffectsRouteImport } from './routes/effects'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as HarmScaleRouteImport } from './routes/harm-scale'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as NeuroRouteImport } from './routes/neuro'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReductionRouteImport } from './routes/reduction'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SubstancesRouteImport } from './routes/substances'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as LogsIdRouteImport } from './routes/logs.$id'
import { Route as LogsNewRouteImport } from './routes/logs.new'
import { Route as SubstanceSlugRouteImport } from './routes/substance.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectsRoute = EffectsRouteImport.update({
  id: '/effects',
  path: '/effects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmScaleRoute = HarmScaleRouteImport.update({
  id: '/harm-scale',
  path: '/harm-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuroRoute = NeuroRouteImport.update({
  id: '/neuro',
  path: '/neuro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReductionRoute = ReductionRouteImport.update({
  id: '/reduction',
  path: '/reduction',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstancesRoute = SubstancesRouteImport.update({
  id: '/substances',
  path: '/substances',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsRoute,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LogsRoute,
} as any)
const LogsNewRoute = LogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LogsRoute,
} as any)
const SubstanceSlugRoute = SubstanceSlugRouteImport.update({
  id: '/substance/$slug',
  path: '/substance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/effects': typeof EffectsRoute
  '/experiences': typeof ExperiencesRoute
  '/harm-scale': typeof HarmScaleRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRouteWithChildren
  '/neuro': typeof NeuroRoute
  '/profile': typeof ProfileRoute
  '/reduction': typeof ReductionRoute
  '/reset': typeof ResetRoute
  '/substances': typeof SubstancesRoute
  '/logs/$id': typeof LogsIdRoute
  '/logs/new': typeof LogsNewRoute
  '/substance/$slug': typeof SubstanceSlugRoute
  '/logs/': typeof LogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/effects': typeof EffectsRoute
  '/experiences': typeof ExperiencesRoute
  '/harm-scale': typeof HarmScaleRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/neuro': typeof NeuroRoute
  '/profile': typeof ProfileRoute
  '/reduction': typeof ReductionRoute
  '/reset': typeof ResetRoute
  '/substances': typeof SubstancesRoute
  '/logs/$id': typeof LogsIdRoute
  '/logs/new': typeof LogsNewRoute
  '/substance/$slug': typeof SubstanceSlugRoute
  '/logs': typeof LogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/effects': typeof EffectsRoute
  '/experiences': typeof ExperiencesRoute
  '/harm-scale': typeof HarmScaleRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRouteWithChildren
  '/neuro': typeof NeuroRoute
  '/profile': typeof ProfileRoute
  '/reduction': typeof ReductionRoute
  '/reset': typeof ResetRoute
  '/substances': typeof SubstancesRoute
  '/logs/$id': typeof LogsIdRoute
  '/logs/new': typeof LogsNewRoute
  '/substance/$slug': typeof SubstanceSlugRoute
  '/logs/': typeof LogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/changelog'
    | '/chat'
    | '/compare'
    | '/downloads'
    | '/effects'
    | '/experiences'
    | '/harm-scale'
    | '/legal'
    | '/login'
    | '/logs'
    | '/neuro'
    | '/profile'
    | '/reduction'
    | '/reset'
    | '/substances'
    | '/logs/$id'
    | '/logs/new'
    | '/substance/$slug'
    | '/logs/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/changelog'
    | '/chat'
    | '/compare'
    | '/downloads'
    | '/effects'
    | '/experiences'
    | '/harm-scale'
    | '/legal'
    | '/login'
    | '/neuro'
    | '/profile'
    | '/reduction'
    | '/reset'
    | '/substances'
    | '/logs/$id'
    | '/logs/new'
    | '/substance/$slug'
    | '/logs'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/changelog'
    | '/chat'
    | '/compare'
    | '/downloads'
    | '/effects'
    | '/experiences'
    | '/harm-scale'
    | '/legal'
    | '/login'
    | '/logs'
    | '/neuro'
    | '/profile'
    | '/reduction'
    | '/reset'
    | '/substances'
    | '/logs/$id'
    | '/logs/new'
    | '/substance/$slug'
    | '/logs/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  DownloadsRoute: typeof DownloadsRoute
  EffectsRoute: typeof EffectsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  HarmScaleRoute: typeof HarmScaleRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRouteWithChildren
  NeuroRoute: typeof NeuroRoute
  ProfileRoute: typeof ProfileRoute
  ReductionRoute: typeof ReductionRoute
  ResetRoute: typeof ResetRoute
  SubstancesRoute: typeof SubstancesRoute
  SubstanceSlugRoute: typeof SubstanceSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effects': {
      id: '/effects'
      path: '/effects'
      fullPath: '/effects'
      preLoaderRoute: typeof EffectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harm-scale': {
      id: '/harm-scale'
      path: '/harm-scale'
      fullPath: '/harm-scale'
      preLoaderRoute: typeof HarmScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuro': {
      id: '/neuro'
      path: '/neuro'
      fullPath: '/neuro'
      preLoaderRoute: typeof NeuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reduction': {
      id: '/reduction'
      path: '/reduction'
      fullPath: '/reduction'
      preLoaderRoute: typeof ReductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substances': {
      id: '/substances'
      path: '/substances'
      fullPath: '/substances'
      preLoaderRoute: typeof SubstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof LogsRoute
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof LogsRoute
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewRouteImport
      parentRoute: typeof LogsRoute
    }
    '/substance/$slug': {
      id: '/substance/$slug'
      path: '/substance/$slug'
      fullPath: '/substance/$slug'
      preLoaderRoute: typeof SubstanceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LogsRouteChildren {
  LogsIdRoute: typeof LogsIdRoute
  LogsNewRoute: typeof LogsNewRoute
  LogsIndexRoute: typeof LogsIndexRoute
}

const LogsRouteChildren: LogsRouteChildren = {
  LogsIdRoute: LogsIdRoute,
  LogsNewRoute: LogsNewRoute,
  LogsIndexRoute: LogsIndexRoute,
}

const LogsRouteWithChildren = LogsRoute._addFileChildren(LogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  DownloadsRoute: DownloadsRoute,
  EffectsRoute: EffectsRoute,
  ExperiencesRoute: ExperiencesRoute,
  HarmScaleRoute: HarmScaleRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRouteWithChildren,
  NeuroRoute: NeuroRoute,
  ProfileRoute: ProfileRoute,
  ReductionRoute: ReductionRoute,
  ResetRoute: ResetRoute,
  SubstancesRoute: SubstancesRoute,
  SubstanceSlugRoute: SubstanceSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
